// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Transaction struct {
	ID        int32            `json:"id"`
	Title     string           `json:"title"`
	Amount    pgtype.Numeric   `json:"amount"`
	Type      string           `json:"type"`
	DueDate   pgtype.Date      `json:"due_date"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
