// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	DeleteTransaction(ctx context.Context, id int32) error
	GetTransaction(ctx context.Context, id int32) (Transaction, error)
	ListTransactions(ctx context.Context) ([]Transaction, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
