// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  title, amount, type, due_date
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, title, amount, type, due_date, created_at
`

type CreateTransactionParams struct {
	Title   string         `json:"title"`
	Amount  pgtype.Numeric `json:"amount"`
	Type    string         `json:"type"`
	DueDate pgtype.Date    `json:"due_date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Title,
		arg.Amount,
		arg.Type,
		arg.DueDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Type,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, title, amount, type, due_date, created_at FROM transactions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id int32) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Type,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, title, amount, type, due_date, created_at FROM transactions
ORDER BY due_date DESC
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Amount,
			&i.Type,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET 
  title = $2,
  amount = $3,
  type = $4,
  due_date = $5
WHERE id = $1
RETURNING id, title, amount, type, due_date, created_at
`

type UpdateTransactionParams struct {
	ID      int32          `json:"id"`
	Title   string         `json:"title"`
	Amount  pgtype.Numeric `json:"amount"`
	Type    string         `json:"type"`
	DueDate pgtype.Date    `json:"due_date"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Title,
		arg.Amount,
		arg.Type,
		arg.DueDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Type,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}
